# Prometheus Configuration for AI Development Platform
# Updated: 2025年6月10日

global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alerts.yml"

scrape_configs:
  # AI API Gateway
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:8000']
    scrape_interval: 10s
    metrics_path: '/api/metrics'

  # AI Services (直接メトリクス収集)
  - job_name: 'ai-services'
    static_configs:
      - targets: ['ollama:11434']
    scrape_interval: 30s
    metrics_path: '/metrics'

  # N8N Workflow Automation
  - job_name: 'n8n'
    static_configs:
      - targets: ['n8n:5678']
    scrape_interval: 30s
    metrics_path: '/metrics'

  # Jupyter Lab
  - job_name: 'jupyter'
    static_configs:
      - targets: ['jupyter:8888']
    scrape_interval: 60s
    metrics_path: '/metrics'

  # PostgreSQL (データベース)
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    scrape_interval: 30s

  # Redis (キャッシュ)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s

  # Prometheus 自身の監視
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Grafana
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
    scrape_interval: 60s

# Global settings
global:
  external_labels:
    monitor: 'ai-development-monitor'
    environment: 'development'

# Alertmanager設定
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - host.docker.internal:9093

# 外部ラベル（マルチクラスタ対応）
external_labels:
  cluster: 'ai-development'
  environment: 'kong-gateway'
  project: 'hotfix-2025' 